### ISSUE TITLE
deploy-minimal on centos ASCII error

### ISSUE THREAD

**Issue by gustavosr98** [erik78se/juju-operators-examples#5]
Thanks for the examples, they are really useful

This is just a side note to be aware for someone who wants to test this examples to develop charms for **centos**
 
I was tweaking the deploy-minimal example to target building the charm for **centos7** and hit this error

```
unit-minimal-1: 19:20:44 ERROR unit.minimal/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-minimal-1/charm/src/charm.py", line 49, in <module>
    main(DeployMinimalCharm)
  File "/var/lib/juju/agents/unit-minimal-1/charm/venv/ops/main.py", line 370, in main
    metadata = (charm_dir / 'metadata.yaml').read_text()
  File "/usr/lib64/python3.6/pathlib.py", line 1197, in read_text
    return f.read()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 23: ordinal not in range(128
```

It ended up being the char "ö" in the `metadata.yaml`

**Comment by erik78se** [comment]
Thanx @gustavosr98 !

Let me know if there is something more that you need help with!
